### ISSUE TITLE
But you already have a Java implementation

### ISSUE THREAD

**Issue by shivenmian** [the-dagger/KotlinMovies#1]
@the-dagger So why do we need an implementation in Kotlin? We should focus on making the app usable rather than doing fancy stuff. 

Also, please open PRs for feature additions, rather than directly committing. And please add the PR number to the commit and mention the change, rather than generic messages like "Initial commit".

I don't know, how to explain all this better. I thought the next goals are clear. What is going on?

**Comment by the-dagger** [comment]
Please don't open duplicate issues.
@mananwason already gave a great example of this same issue in #420, please refer to it. 👍
